// Code generated by hertz generator.

package main

import (
	"ByteTech-7815/douyin-zhgg/cmd/api/biz/middleware"
	"ByteTech-7815/douyin-zhgg/cmd/api/biz/rpc"
	"github.com/cloudwego/hertz/pkg/app/server"
)

func Init() {
	middleware.InitJWT()
	rpc.InitRPC()
}

func main() {
	Init()
	h := server.New(
		server.WithHostPorts(":8080"),
		server.WithHandleMethodNotAllowed(true),
	)

	register(h)
	h.Spin()
}
